### PR TITLE
Leaderboard example - fix #1

### LINKED ISSUE #1: example
Could you provide an example like [this](https://github.com/reactjs/react-meteor/tree/master/examples/leaderboard).

PS: Now `grigio:babel` compiles `.jsx` by default

### PR DESCRIPTION
**Pull request by grigio**

### CODE REVIEW

**Comment by grigio** [comment]
@lourd  It works but I've still this warning around

```
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of Leaderboard. See http://fb.me/react-warning-keys for more information.
```

**Comment by cmnjcs** [comment]
Hi @grigio--looking at [leaderboard.jsx](https://github.com/grigio/meteor-react/blob/192a7b27a64bc1098451a530bdde2fe79c8882e5/examples/leaderboard/leaderboard.jsx), my guess is that React doesn't like that each element in `children` (the top-most elements, so the two `div`s and the `span`) doesn't have a unique ID. That's the only array or iterator I see, and none of its immediate elements have unique IDs.

If I were doing this, what I'd probably do would look something like:

```
render: function() {
    var thingToDisplay;
    if(this.state.selectedName) {
        thingToDisplay = details div (lines 62-69)
    } else {
        thingToDisplay = nothing to select div (line 75)
    }
    return (
        leaderboard div (lines 55-57)
        thingToDisplay
        loggedIn span (line 80)

    )

}
```

Does that help?

**Comment by grigio** [comment]
@cmnjcs thanks. However it seems `return ( ... )` can't return more than one root element. I'm still get used to react :)

**Comment by cmnjcs** [comment]
Then what you need to do is wrap everything else in an element (usually a `main` or `div`, from what I've seen) like you did at line 83.

**Comment by alexedev** [comment]
Thank you for the example.

I created a repo with a modified version.
https://github.com/buduguru/meteor-react-es6-leaderboard
Especially I modified the client code a bit (according to ES6) and added many comments to understand it better (I just started to learn both React and ES6 features).
Please look at comments in this file https://github.com/buduguru/meteor-react-es6-leaderboard/blob/master/client/client.jsx and let me know if I understand it right.

But I definitely have problems understanding this construction:

``` javascript
render() {
      //create object through destructuring (ES6)
      // we start not from "key" but "name" because we needed "key" only
      // to define the value of className
      // in this case "rest" includes "className" and "onClick" properties
      const { name, score, ...rest } = this.props;
      let classString = `player ${rest.className}`;
      return <div {...rest} className={classString}>
        <span className="name">{name}</span>
        <span className="score">{score}</span>
      </div>;
    }
```

why cant we do it like this?:

``` javascript
render() {
      const { name, score, className, onClick } = this.props;
      let classString = `player ${className}`;
      return <div {onClick} className={classString}>
        <span className="name">{name}</span>
        <span className="score">{score}</span>
      </div>;
    }
```

This code does not work and I can not get it why.

**Comment by grigio** [comment]
@buduguru yeah it doesn't follow strictly the new js features, It is the ES6 [destructuring assignement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment) feature.

Maybe it's a JSX limitation..
`return <div {onClick} className={classString}>`
it should work like this:
`return <div {...onClick} className={classString}>`

EDIT: or maybe because `rest.className` isn't the third element in the obj

**Comment by alexedev** [comment]
@grigio thanks, I will try it.

**Comment by grigio** [comment]
@lourd @cmnjcs can this be merged?

**Pull request merged**
